<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- Prevent this project from importing Directory.Build.targets -->
    <ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets>
    <ApplicationIcon>Logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="BuildTimestamp" Value="$([System.DateTime]::Now.ToString())" />
    <Content Include="Logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LLVMSharp">
      <HintPath>lib\net10.0\LLVMSharp.dll</HintPath>
    </Reference>
    <Reference Include="LLVMSharp.Interop">
      <HintPath>lib\net10.0\LLVMSharp.Interop.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>lib\netstandard2.0\Mono.Cecil.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="CopyLibLLVM" AfterTargets="Build">
    <Copy SourceFiles="lib\win-x64\libLLVM.dll" DestinationFiles="$(TargetDir)libLLVM.dll" SkipUnchangedFiles="true" />
  </Target>

</Project>
